export const DEFAULT_EDITORIAL = {
  registeredOffice: "Railway Link Road,\nKozhikkode-2, Kerala",
  managingDirector: "Sayyid Sadiq Ali Shihab Thangal",
  chiefEditor: "Abdul Hameed Faizi\nAmbalakkadavu",
  gulfChairman: "Dr. Abdul Rahiman Olavattoor",
  gulfEditorInCharge: "Midlaj Rahmani",
  subEditors: ["Abdul Vajid Rahmani", "Haneef Rahmani Panangangara", "EM Shareef Hudawi Muthuthala"],
  management: [
    "Shuaib Koya Thangal", "Yahya Thalangara", "Abdul Razak Valanchery",
    "Hyder Ali Hudawi", "Abdul Rahman Thangal", "Hussain Darimi", "Abdul Hakeem Faizi",
  ],
  distribution: "Tawseel Distribution LLC",
  printingAt: "United Printing Press, Abudhabi",
  licenseNo: "1/109645/33658",
  licenseBody: "National media Council, UAE",
  uaeAddress: "P. B. No: 5774, Dubai",
  uaeTel: "+971 56 1559951",
  uaeEditorEmail: "editor@gulfsathyadhara.com",
  uaeSubscriptionEmail: "subscription@gulfsathyadhara.com",
  qatar: ["Aboobacker Qasimi, Mob: 974 55510615", "Muneer Kalavu, Mob: 97433698681"],
  kuwait: ["Abdul Hakeem Moulavi, Mob: 96567682761"],
  bahrain: ["Ashraf Anwari Chelakkara, Mob: 0097333450553"],
  saudiArabia: ["Aboobacker Faizy Chengamanad, Mob: 9665 0928 4117"],
  oman: ["Samad Faizy, Mob: 9689 621 9265", "Shakeer Faizy, Mob: 9689 307 5758"],
  designLayout: "Abu Hatem",
  designStudio: "D360",
};
